export type VehicleStatus = "online" | "warning" | "critical" | "offline";

export interface SensorHealth {
  camera: "OK" | "Warning" | "Error";
  lidar: "OK" | "Warning" | "Error";
  radar: "OK" | "Warning" | "Error";
  gps: "OK" | "Warning" | "Error";
  esp32: "Connected" | "Connecting" | "Disconnected";
  aiModel: "Running" | "Idle" | "Error";
}

export interface HEMMVehicle {
  id: string;
  name: string;
  model: string;
  status: VehicleStatus;
  online: boolean;
  speed: number;
  gear: "P" | "R" | "N" | "D" | "BST";
  clearance: number;
  ttc: number;
  heading: number;
  latitude: number;
  longitude: number;
  zone: string;
  payload: number;
  power: number;
  fuel: number;
  mapX: number; // % position on mine map (0 - 100)
  mapY: number; // % position on mine map (0 - 100)
  sensors: SensorHealth;
  operator: string;
  shiftHours: number;
  distanceToday: number;
  lastUpdated: string;
  alertMessage?: string;
  image: string;
  routeId?: string;
  routeProgress?: number;
  routeDirection?: 1 | -1;
  currentSegment?: number;
  progressAlongSegment?: number;
  baseSpeed?: number;
}

export interface FleetAlert {
  id: string;
  time: string;
  vehicleId: string;
  alertType: "Person Detected" | "Speed Limit" | "Geofence" | "Proximity" | "Sensor" | "Obstacle";
  message: string;
  severity: "Critical" | "Warning" | "Info";
  zone: string;
}

export interface FleetKPIs {
  totalDumpers: number;
  onlineDumpers: number;
  offlineDumpers: number;
  activeAlerts: number;
  criticalAlerts: number;
  warningAlerts: number;
  totalDistanceToday: number;
  distanceVsYesterday: number;
  avgSpeed: number;
  speedLimitStatus: "Within Limit" | "Approaching Limit" | "Exceeded";
  systemUptime: number;
  systemStatus: "All Systems Operational" | "Subsystem Degraded";
}

export const INITIAL_VEHICLES: HEMMVehicle[] = [
  {
    id: "D-01",
    name: "HEMM D-01",
    model: "CAT 797F Ultra-Class",
    status: "online",
    online: true,
    speed: 10.0,
    baseSpeed: 10.0,
    gear: "D",
    clearance: 12.4,
    ttc: 9.8,
    heading: 250,
    latitude: 18.6291,
    longitude: 73.8012,
    zone: "North Bench Ramp",
    payload: 22.0,
    power: 96,
    fuel: 88,
    mapX: 60.5,
    mapY: 25.5,
    routeId: "west_switchback_d01",
    routeProgress: 0.05,
    routeDirection: 1,
    currentSegment: 0,
    progressAlongSegment: 0.10,
    sensors: {
      camera: "OK",
      lidar: "OK",
      radar: "OK",
      gps: "OK",
      esp32: "Connected",
      aiModel: "Running",
    },
    operator: "Rajesh Sharma",
    shiftHours: 6.4,
    distanceToday: 34.2,
    lastUpdated: "Just now",
    image: "/images/hemm_dumper_truck.jpg",
  },
  {
    id: "D-02",
    name: "HEMM D-02",
    model: "CAT 797F Ultra-Class",
    status: "online",
    online: true,
    speed: 8.0,
    baseSpeed: 8.0,
    gear: "D",
    clearance: 7.1,
    ttc: 4.6,
    heading: 105,
    latitude: 18.6288,
    longitude: 73.8115,
    zone: "East Transfer Spur",
    payload: 20.4,
    power: 89,
    fuel: 79,
    mapX: 71.5,
    mapY: 39.0,
    routeId: "east_switchback_d02",
    routeProgress: 0.05,
    routeDirection: 1,
    currentSegment: 0,
    progressAlongSegment: 0.10,
    sensors: {
      camera: "OK",
      lidar: "OK",
      radar: "OK",
      gps: "OK",
      esp32: "Connected",
      aiModel: "Running",
    },
    operator: "Kavita Patil",
    shiftHours: 7.1,
    distanceToday: 31.5,
    lastUpdated: "Just now",
    image: "/images/hemm_dumper_truck.jpg",
  },
  {
    id: "D-03",
    name: "HEMM D-03",
    model: "CAT 797F Ultra-Class",
    status: "online",
    online: true,
    speed: 7.5,
    baseSpeed: 7.5,
    gear: "D",
    clearance: 12.0,
    ttc: 10.5,
    heading: 95,
    latitude: 18.6274,
    longitude: 73.8061,
    zone: "Haul Road A",
    payload: 18.5,
    power: 92,
    fuel: 85,
    mapX: 69.2,
    mapY: 12.0,
    routeId: "hazard_d03",
    routeProgress: 0.05,
    routeDirection: 1,
    currentSegment: 0,
    progressAlongSegment: 0.10,
    sensors: {
      camera: "OK",
      lidar: "OK",
      radar: "OK",
      gps: "OK",
      esp32: "Connected",
      aiModel: "Running",
    },
    operator: "Vikram Deshmukh",
    shiftHours: 8.2,
    distanceToday: 38.6,
    lastUpdated: "Just now",
    image: "/images/hemm_dumper_truck.jpg",
  },
  {
    id: "D-04",
    name: "HEMM D-04",
    model: "Komatsu 930E-5",
    status: "warning",
    online: true,
    speed: 12.0,
    baseSpeed: 12.0,
    gear: "D",
    clearance: 6.8,
    ttc: 3.5,
    heading: 37,
    latitude: 18.6252,
    longitude: 73.8038,
    zone: "Kirandul Pit Haul Highway",
    payload: 19.8,
    power: 84,
    fuel: 67,
    mapX: 17.5,
    mapY: 81.0,
    routeId: "sw_pit_d04",
    routeProgress: 0.02,
    routeDirection: 1,
    currentSegment: 0,
    progressAlongSegment: 0.10,
    sensors: {
      camera: "OK",
      lidar: "OK",
      radar: "OK",
      gps: "OK",
      esp32: "Connected",
      aiModel: "Running",
    },
    operator: "Anil Jadhav",
    shiftHours: 5.8,
    distanceToday: 29.4,
    lastUpdated: "4s ago",
    alertMessage: "Approach speed elevated on descending ramp grade",
    image: "/images/hemm_dumper_truck.jpg",
  },
  {
    id: "D-05",
    name: "HEMM D-05",
    model: "CAT 797F Ultra-Class",
    status: "warning",
    online: true,
    speed: 7.0,
    baseSpeed: 7.0,
    gear: "D",
    clearance: 11.0,
    ttc: 8.2,
    heading: 180,
    latitude: 18.6315,
    longitude: 73.8078,
    zone: "Deposit 5 Central Arterial",
    payload: 24.2,
    power: 91,
    fuel: 72,
    mapX: 66.8,
    mapY: 4.5,
    routeId: "central_haul_d05",
    routeProgress: 0.02,
    routeDirection: 1,
    currentSegment: 0,
    progressAlongSegment: 0.10,
    sensors: {
      camera: "OK",
      lidar: "OK",
      radar: "OK",
      gps: "OK",
      esp32: "Connected",
      aiModel: "Running",
    },
    operator: "Suresh Gaikwad",
    shiftHours: 8.5,
    distanceToday: 36.8,
    lastUpdated: "5s ago",
    alertMessage: "Speed 7 km/h (ramp speed limit 20 km/h)",
    image: "/images/hemm_dumper_truck.jpg",
  },
  {
    id: "D-06",
    name: "HEMM D-06",
    model: "CAT 797F Ultra-Class",
    status: "online",
    online: true,
    speed: 9.0,
    baseSpeed: 9.0,
    gear: "D",
    clearance: 14.8,
    ttc: 12.0,
    heading: 110,
    latitude: 18.6234,
    longitude: 73.8021,
    zone: "Upper Approach Corridor",
    payload: 21.0,
    power: 88,
    fuel: 80,
    mapX: 27.5,
    mapY: 68.5,
    routeId: "sw_upper_d06",
    routeProgress: 0.05,
    routeDirection: 1,
    currentSegment: 0,
    progressAlongSegment: 0.10,
    sensors: {
      camera: "OK",
      lidar: "OK",
      radar: "OK",
      gps: "OK",
      esp32: "Connected",
      aiModel: "Running",
    },
    operator: "Prakash More",
    shiftHours: 6.9,
    distanceToday: 27.1,
    lastUpdated: "6s ago",
    image: "/images/hemm_dumper_truck.jpg",
  },
  {
    id: "D-07",
    name: "HEMM D-07",
    model: "Komatsu 930E-5",
    status: "online",
    online: true,
    speed: 11.0,
    baseSpeed: 11.0,
    gear: "D",
    clearance: 16.5,
    ttc: 14.1,
    heading: 180,
    latitude: 18.6225,
    longitude: 73.8092,
    zone: "Deposit 5 South Terraces Loop",
    payload: 0.0,
    power: 95,
    fuel: 91,
    mapX: 66.0,
    mapY: 38.0,
    routeId: "south_artery_d07",
    routeProgress: 0.05,
    routeDirection: 1,
    currentSegment: 0,
    progressAlongSegment: 0.10,
    sensors: {
      camera: "OK",
      lidar: "OK",
      radar: "OK",
      gps: "OK",
      esp32: "Connected",
      aiModel: "Running",
    },
    operator: "Mahesh Naik",
    shiftHours: 7.4,
    distanceToday: 26.5,
    lastUpdated: "3s ago",
    image: "/images/hemm_dumper_truck.jpg",
  },
  {
    id: "D-08",
    name: "HEMM D-08",
    model: "CAT 797F Ultra-Class",
    status: "online",
    online: true,
    speed: 8.0,
    baseSpeed: 8.0,
    gear: "D",
    clearance: 16.5,
    ttc: 14.0,
    heading: 105,
    latitude: 18.6241,
    longitude: 73.8055,
    zone: "East Ridge to Green Pit Valley",
    payload: 17.2,
    power: 87,
    fuel: 64,
    mapX: 82.5,
    mapY: 37.5,
    routeId: "east_switchback_d08",
    routeProgress: 0.20,
    routeDirection: 1,
    currentSegment: 2,
    progressAlongSegment: 0.40,
    sensors: {
      camera: "OK",
      lidar: "OK",
      radar: "OK",
      gps: "OK",
      esp32: "Connected",
      aiModel: "Running",
    },
    operator: "Deepak Shinde",
    shiftHours: 8.8,
    distanceToday: 24.5,
    lastUpdated: "Just now",
    image: "/images/hemm_dumper_truck.jpg",
  },
  {
    id: "D-09",
    name: "HEMM D-09",
    model: "CAT 797F Ultra-Class",
    status: "online",
    online: true,
    speed: 8.0,
    baseSpeed: 8.0,
    gear: "D",
    clearance: 20.0,
    ttc: 18.0,
    heading: 140,
    latitude: 18.632,
    longitude: 73.804,
    zone: "North Pit Cut Bench",
    payload: 25.0,
    power: 98,
    fuel: 85,
    mapX: 66.8,
    mapY: 24.0,
    routeId: "north_pit_d09",
    routeProgress: 0.05,
    routeDirection: 1,
    currentSegment: 0,
    progressAlongSegment: 0.10,
    sensors: {
      camera: "OK",
      lidar: "OK",
      radar: "OK",
      gps: "OK",
      esp32: "Connected",
      aiModel: "Running",
    },
    operator: "Sachin Kadam",
    shiftHours: 5.1,
    distanceToday: 21.0,
    lastUpdated: "7s ago",
    image: "/images/hemm_dumper_truck.jpg",
  },
  {
    id: "D-10",
    name: "HEMM D-10",
    model: "Komatsu 930E-5",
    status: "online",
    online: true,
    speed: 9.0,
    baseSpeed: 9.0,
    gear: "D",
    clearance: 15.2,
    ttc: 11.5,
    heading: 130,
    latitude: 18.621,
    longitude: 73.804,
    zone: "Southwest Quarry Spur",
    payload: 26.5,
    power: 94,
    fuel: 82,
    mapX: 27.5,
    mapY: 68.5,
    routeId: "sw_spur_d10",
    routeProgress: 0.05,
    routeDirection: 1,
    currentSegment: 0,
    progressAlongSegment: 0.10,
    sensors: {
      camera: "OK",
      lidar: "OK",
      radar: "OK",
      gps: "OK",
      esp32: "Connected",
      aiModel: "Running",
    },
    operator: "Nitin Bhalerao",
    shiftHours: 6.2,
    distanceToday: 22.8,
    lastUpdated: "8s ago",
    image: "/images/hemm_dumper_truck.jpg",
  },
  {
    id: "D-11",
    name: "HEMM D-11",
    model: "CAT 797F Ultra-Class",
    status: "online",
    online: true,
    speed: 8.0,
    baseSpeed: 8.0,
    gear: "D",
    clearance: 15.0,
    ttc: 12.0,
    heading: 180,
    latitude: 18.635,
    longitude: 73.815,
    zone: "Heavy Maintenance Bay 3",
    payload: 21.5,
    power: 92,
    fuel: 85,
    mapX: 77.0,
    mapY: 26.8,
    routeId: "workshop_bay_d11",
    routeProgress: 0.0,
    routeDirection: 1,
    currentSegment: 0,
    progressAlongSegment: 0.0,
    sensors: {
      camera: "OK",
      lidar: "OK",
      radar: "OK",
      gps: "OK",
      esp32: "Connected",
      aiModel: "Running",
    },
    operator: "Vikrant Patil",
    shiftHours: 4.5,
    distanceToday: 18.2,
    lastUpdated: "Just now",
    image: "/images/hemm_dumper_truck.jpg",
  },
  {
    id: "D-12",
    name: "HEMM D-12",
    model: "Komatsu 930E-5",
    status: "online",
    online: true,
    speed: 8.0,
    baseSpeed: 8.0,
    gear: "D",
    clearance: 14.5,
    ttc: 11.5,
    heading: 180,
    latitude: 18.636,
    longitude: 73.816,
    zone: "Heavy Maintenance Bay 4",
    payload: 23.0,
    power: 88,
    fuel: 78,
    mapX: 78.5,
    mapY: 28.5,
    routeId: "workshop_bay_d12",
    routeProgress: 0.0,
    routeDirection: 1,
    currentSegment: 0,
    progressAlongSegment: 0.0,
    sensors: {
      camera: "OK",
      lidar: "OK",
      radar: "OK",
      gps: "OK",
      esp32: "Connected",
      aiModel: "Running",
    },
    operator: "Sunil Mane",
    shiftHours: 3.8,
    distanceToday: 15.6,
    lastUpdated: "Just now",
    image: "/images/hemm_dumper_truck.jpg",
  },
];

export const RECENT_ALERTS: FleetAlert[] = [
  {
    id: "alt-01",
    time: "15:22:41",
    vehicleId: "D-03",
    alertType: "Person Detected",
    message: "Human detected within 8 m in forward collision path",
    severity: "Critical",
    zone: "Haul Road A",
  },
  {
    id: "alt-02",
    time: "15:18:05",
    vehicleId: "D-05",
    alertType: "Speed Limit",
    message: "Speed 28 km/h (speed limit 20 km/h on incline)",
    severity: "Warning",
    zone: "Upper Crusher Road",
  },
  {
    id: "alt-03",
    time: "15:14:23",
    vehicleId: "D-08",
    alertType: "Geofence",
    message: "Entered restricted zone — Scheduled Blasting Sector A-3",
    severity: "Critical",
    zone: "Restricted Zone",
  },
  {
    id: "alt-04",
    time: "15:10:11",
    vehicleId: "D-02",
    alertType: "Proximity",
    message: "Vehicle too close (5 m) — Lead vehicle deceleration",
    severity: "Warning",
    zone: "East Transfer Spur",
  },
  {
    id: "alt-05",
    time: "15:05:37",
    vehicleId: "D-06",
    alertType: "Sensor",
    message: "LiDAR not responding — Sensor signal degradation",
    severity: "Warning",
    zone: "South Incline Bench",
  },
];

export const INITIAL_KPIS: FleetKPIs = {
  totalDumpers: 12,
  onlineDumpers: 10,
  offlineDumpers: 2,
  activeAlerts: 3,
  criticalAlerts: 1,
  warningAlerts: 2,
  totalDistanceToday: 248.6,
  distanceVsYesterday: 12,
  avgSpeed: 18.4,
  speedLimitStatus: "Within Limit",
  systemUptime: 99.8,
  systemStatus: "All Systems Operational",
};

export const FLEET_UTILIZATION = {
  rate: 83,
  runningCount: 10,
  runningPct: 83,
  idleCount: 1,
  idlePct: 8,
  offlineCount: 1,
  offlinePct: 8,
};
